fos_rest:
    disable_csrf_role: IS_AUTHENTICATED_ANONYMOUSLY
    allowed_methods_listener: true
    param_fetcher_listener: true
    body_listener: true
    view:
      view_response_listener: 'force'
    versioning: true
    format_listener:
      enabled: true
      rules:
        - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
    body_converter:
      enabled: true
    serializer:
      serialize_null: true
    exception:
      enabled: true
    zone:
      - { path: ^/api/* }
